### ISSUE TITLE
Error al subir un comprobante de nombre largo

### ISSUE THREAD

**Issue by J0hnG4lt** [cadena-si-usb/SiraDex#16]
Commit: bb966bc4ea1757bd2d4247a3d330f0fcd1271995

`<type 'exceptions.IOError'> [Errno 36] File name too long: '/home/www-data/web2py/applications/SiraDex/uploads/no_table.c0mpr0bant3_1/b2/no_table.c0mpr0bant3_1.b27722637722edb3.4272756365204275656e6f206465204d6573717569746120616e6420416c61737461697220536d6974682d546865206469637461746f7227732068616e64626f6f6b205f2077687920626164206265686176696f7220697320616c6d6f737420616c7761797320676f6f6420706f6c69746963732d4e657720596f726b2c204e59205075626c696341666661697273202832303131292e706466.pdf`

`
Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/home/www-data/web2py/applications/SiraDex/controllers/producto.py", line 793, in <module>
  File "/home/www-data/web2py/gluon/globals.py", line 417, in <lambda>
    self._caller = lambda f: f()
  File "/home/www-data/web2py/applications/SiraDex/controllers/producto.py", line 195, in agregar
    if form.process().accepted:
  File "/home/www-data/web2py/gluon/html.py", line 2298, in process
    self.validate(**kwargs)
  File "/home/www-data/web2py/gluon/html.py", line 2236, in validate
    if self.accepts(**kwargs):
  File "/home/www-data/web2py/gluon/sqlhtml.py", line 1662, in accepts
    field.uploadfolder)
  File "/home/www-data/web2py/gluon/packages/dal/pydal/objects.py", line 1532, in store
    dest_file = open(pathfilename, 'wb')
IOError: [Errno 36] File name too long: '/home/www-data/web2py/applications/SiraDex/uploads/no_table.c0mpr0bant3_1/b2/no_table.c0mpr0bant3_1.b27722637722edb3.4272756365204275656e6f206465204d6573717569746120616e6420416c61737461697220536d6974682d546865206469637461746f7227732068616e64626f6f6b205f2077687920626164206265686176696f7220697320616c6d6f737420616c7761797320676f6f6420706f6c69746963732d4e657720596f726b2c204e59205075626c696341666661697273202832303131292e706466.pdf'
`

**Comment by RumbosN** [comment]
de cuantos caracteres era el nombre?

**Comment by RumbosN** [comment]
se coloco que el nombre debia tener maximo 50 caracteres. Linea 301 en modificar producto y 299 en agregar producto
