### ISSUE TITLE
Error al intentar crear un producto con un tipo de actividad con un campo adicional (Cédula)

### ISSUE THREAD

**Issue by J0hnG4lt** [cadena-si-usb/SiraDex#31]
Probado en siradex.dex.usb.ve

Caso de Prueba: CP10-ES5-FA3

Nombre del campo adicional obligatorio: Cédula
Tipo del campo: Cédula

`Error ticket for "SiraDex"
Ticket ID
201.211.38.172.2017-03-09.21-37-39.6d1b4eb7-9a24-4aad-8b16-1ce269a634d6

<type 'exceptions.SyntaxError'> Field: invalid field name: Cédula, use rname for "funny" names

Version
web2py™	Version 2.14.6-stable+timestamp.2016.05.10.00.21.47
Python	Python 2.7.9: /usr/bin/python (prefix: /usr)

Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/home/www-data/web2py/applications/SiraDex/controllers/producto.py", line 793, in <module>
  File "/home/www-data/web2py/gluon/globals.py", line 417, in <lambda>
    self._caller = lambda f: f()
  File "/home/www-data/web2py/applications/SiraDex/controllers/producto.py", line 150, in agregar
    elif tipo_campo in ['Cedula']:            fields.append(Field(nombre,'string',label=rows_campo.nombre+" (*)",requires=[IS_NOT_EMPTY(),IS_MATCH('\d{2}.\d{3}.\d{3}$', error_message='CI inválida, debe ser: XX.XXX.XXX')]))
  File "/home/www-data/web2py/gluon/packages/dal/pydal/objects.py", line 1438, in __init__
    'use rname for "funny" names' % fieldname)
SyntaxError: Field: invalid field name: Cédula, use rname for "funny" names`

**Comment by J0hnG4lt** [comment]
En la rama prometheus hay un intento de arreglar estos problemas con campos adicionales.
Ver el commit: 35e98d749913f3363609ed370468d68a2075cf65
Modifiqué la base de datos para esto.
